### ISSUE TITLE
Asterisk

### ISSUE THREAD

**Issue by gamecompiler** [QDeltaSoft/qradiolink#2]
Hi, how do i enable the Asterisk feature?
And how do i dial a number when using Asterisk?

Thanks in advance,
gamecompiler

**Comment by kantooon** [comment]
Asterisk support has been disabled in the latest version, so you would need to go through the code and re-enable it. The reason was that Asterisk and Iaxclient were deemed to be very heavy for this particular application, and instead a simpler, Mumble based protocol was implemented with less features but also more lightweight.
Also, you should be aware that development has stopped a while ago and I'm no longer actively supporting qradiolink.
